version: '2.1'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=parser_app
      - POSTGRES_PASSWORD=parser_app_password
      - POSTGRES_DB=parser
    ports:
      - "5442:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d parser"]
      interval: 10s
      timeout: 15s
      retries: 12
